name: Build Projects

on:
  pull_request:
  push:
    branches:
    - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Geode CLI
      uses: geode-sdk/cli/.github/actions/setup@main
      with:
        version: "latest"

    - uses: actions/checkout@v4
      with:
        repository: "qimiko/geode"
        ref: "gdps"
        path: ${{ github.workspace }}/geode-sdk-clone

    - uses: robinraju/release-downloader@v1
      with:
        repository: "qimiko/geode"
        tag: "nightly"
        fileName: "geode-*-+(win|android32).zip"
        out-file-path: "${{ github.workspace }}/geode-sdk-clone/bin/nightly"
        extract: true

    - name: Load CPM cache
      id: cache-cpm
      uses: actions/cache@v3
      with:
        path: ~/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-

    - name: Setup subprojects
      shell: bash
      run: ${{ github.workspace }}/setup.sh

    - name: Build subprojects
      shell: bash
      run: ${{ github.workspace }}/build.sh
      env:
        GEODE_SDK: ${{ github.workspace }}/geode-sdk-clone

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-results
        path: ${{ github.workspace }}/out/

